### ISSUE TITLE
这问题该怎么解决

### ISSUE THREAD

**Issue by ithjz** [Martin404/PayMap#5]
`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PayMap Maven Webapp 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.unionpay:unionpay-acp-sdk:jar:1.0.0 is missing, no dependency information available
[WARNING] The POM for com.psbc:psbc-merchant-toolkit:jar:1.0.1 is missing, no dependency information available
[WARNING] The POM for com.ceb:ceb-merchant:jar:0.01 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.132 s
[INFO] Finished at: 2018-02-05T16:29:15+08:00
[INFO] Final Memory: 14M/164M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project PayMap: Could not resolve dependencies for project com.hugnew:PayMap:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.unionpay:unionpay-acp-sdk:jar:1.0.0, com.psbc:psbc-merchant-toolkit:jar:1.0.1, com.ceb:ceb-merchant:jar:0.01: Failure to find com.unionpay:unionpay-acp-sdk:jar:1.0.0 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

**Comment by ithjz** [comment]
Failed to execute goal on project PayMap: Could not resolve dependencies for project com.hugnew:PayMap:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.unionpay:unionpay-acp-sdk:jar:1.0.0, com.psbc:psbc-merchant-toolkit:jar:1.0.1, com.ceb:ceb-merchant:jar:0.01: Failure to find com.unionpay:unionpay-acp-sdk:jar:1.0.0 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]

**Comment by Martin404** [comment]
没找到相关依赖包，如果发现缺少JAR包，可以从WEB-INF目录下找到，请自行更新到你本地Maven库中
