### ISSUE TITLE
大佬，这个sps_member.sql 脚本 貌似出了点问题。

### ISSUE THREAD

**Issue by ghost** [Martin404/PayMap#6]
CREATE TABLE sps_db.sps_member(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT ''用户ID'',
  username VARCHAR(200) DEFAULT '''' COMMENT ''用户名'',
-------------------------------修改之后的--------------------------------------------

CREATE TABLE sps_db.sps_member(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  username VARCHAR(200) DEFAULT '''' COMMENT '用户名',
  userCode VARCHAR(200) DEFAULT '''' COMMENT '用户唯一推广编码',
  userLabel INT(11) DEFAULT 1 COMMENT '用户标签',
  `password` VARCHAR(1000) DEFAULT '''' COMMENT '用户密码',
  salt VARCHAR(100) DEFAULT '''' COMMENT '密码加密的盐',
  status INT(11) DEFAULT 1 COMMENT '用户状态：1 正常 /0 禁用',
  grade INT(11) DEFAULT 1 COMMENT '会员级别',
  realName VARCHAR(100) DEFAULT '''' COMMENT '真实姓名',
  nickName VARCHAR(100) DEFAULT '''' COMMENT '昵称',
  showImage VARCHAR(500) DEFAULT '''' COMMENT '用户头像',
  birthday BIGINT(20) DEFAULT 0 COMMENT '生日',
  birthdayStr VARCHAR(100) DEFAULT '0' COMMENT '生日字符串',
  sex INT(11) DEFAULT 0 COMMENT '性别:0 女 / 1 男',
  email VARCHAR(100) DEFAULT '''' COMMENT '邮箱',
  emailStatus INT(11) NOT NULL DEFAULT 0 COMMENT '邮箱校验状态：0 未校验 / 1 校验通过',
  cellphone VARCHAR(50) DEFAULT '''' COMMENT '手机号',
  phoneStatus INT(11) NOT NULL DEFAULT 0 COMMENT '手机号校验状态：0 未校验 / 1 校验通过',
  telephone VARCHAR(50) DEFAULT '''' COMMENT '电话号码',
  province VARCHAR(50) DEFAULT '''' COMMENT '所在省份',
  city VARCHAR(100) DEFAULT '''' COMMENT '所在城市',
  country VARCHAR(200) DEFAULT '''' COMMENT '所在区县',
  address VARCHAR(1000) DEFAULT '''' COMMENT '具体详细地址',
  otherInfo TEXT DEFAULT NULL COMMENT '更多其他信息',
  createTime BIGINT(20) DEFAULT 0 COMMENT '添加日期:Unix时间戳',
  modifyTime BIGINT(20) DEFAULT 0 COMMENT '最后更新日期：Unix时间戳',
  idCardNo VARCHAR(50) DEFAULT '''' COMMENT '证件号码',
  referee BIGINT(20) DEFAULT 0 COMMENT '介绍人ID',
  amount DECIMAL(18, 2) DEFAULT 0.00 COMMENT '现金账户余额',
  points INT(11) DEFAULT 0 COMMENT '剩余积分',
  orderCount INT(11) DEFAULT 0 COMMENT '交易次数',
  odooId INT(20) DEFAULT 0 COMMENT '对应odoo的id',
  orderAmount DECIMAL(10, 2) DEFAULT 0.00 COMMENT '所购订单总金额',
  gradeAmount DECIMAL(10, 2) DEFAULT 0.00 COMMENT '当前等级下花费的总金额',
  gradeChangeTime BIGINT(20) DEFAULT 0 COMMENT '会员等级改变时间',
  memberMark INT(11) DEFAULT 0 COMMENT '会员标记,0-普通会员,1-特殊关注会员',
  memberLabel VARCHAR(100) DEFAULT '0' COMMENT '会员标签',
  labelReason VARCHAR(100) DEFAULT '0' COMMENT '标记原因',
  phoneUpdateTime BIGINT(20) DEFAULT 0 COMMENT '手机更改时间',
  emailUpdateTime BIGINT(20) DEFAULT 0 COMMENT '邮箱更改时间',
  del BIT(1) DEFAULT b'0',
  PRIMARY KEY (id),
  INDEX cellphone (cellphone),
  INDEX email (email),
  INDEX username (username)
)
  ENGINE = INNODB
  CHARACTER SET utf8
  COLLATE utf8_general_ci
  COMMENT = '用户信息表';

**Comment by Martin404** [comment]
单引号多引号 应该是不同的client支持的不一样引起兼容异常，一般情况下都是可以的。
